{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "base_local_planner",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "base_local_planner-1.17.1.jar",
          "url": "base_local_planner-1.17.1.jar",
          "size": 793,
          "sha512": "ac9fdf1429c39658bd39f8744d55d07eaeb37ae9f970aa1c1354a23dfc7b27cc57fe709e3d061d67fc5bbd6e02ac2f98cc921559da6553e395b719ac0d319e59",
          "sha256": "138203a1f4029a4bffba424a143416a78e1cea561134d384b96658a9b4dd921f",
          "sha1": "4b1a4434afd9b9a356f602d0e117010416cfd7bb",
          "md5": "efb854a67534ad3e047934edb16e5a2b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "dynamic_reconfigure",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "base_local_planner-1.17.1.jar",
          "url": "base_local_planner-1.17.1.jar",
          "size": 793,
          "sha512": "ac9fdf1429c39658bd39f8744d55d07eaeb37ae9f970aa1c1354a23dfc7b27cc57fe709e3d061d67fc5bbd6e02ac2f98cc921559da6553e395b719ac0d319e59",
          "sha256": "138203a1f4029a4bffba424a143416a78e1cea561134d384b96658a9b4dd921f",
          "sha1": "4b1a4434afd9b9a356f602d0e117010416cfd7bb",
          "md5": "efb854a67534ad3e047934edb16e5a2b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base_local_planner-1.17.1-sources.jar",
          "url": "base_local_planner-1.17.1-sources.jar",
          "size": 722,
          "sha512": "af41797984a698bb3cbd0d1f035e569b3a067c8415694039e04b6f47ab2bfda30ca70ba3d8cd6078c00f56953f052d275c0a4e5aaef4a755d1d8d021fff9fbad",
          "sha256": "e2d9dd323e22f2884d6d84f9f89488acb4e974398e01a005a037f615584dd71e",
          "sha1": "f8ab1bc3c8227f173c8cc6ba229fa4b3ab77aacd",
          "md5": "4f3963d3598d4ae0895d3dcb43a6da6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "base_local_planner-1.17.1-javadoc.jar",
          "url": "base_local_planner-1.17.1-javadoc.jar",
          "size": 107645,
          "sha512": "45f7c74bb3453dcb070b1ebd7262993a61102746c677f0f91e20194cccf0e8b6f2b9e76cd185ff5b842d3b17b32f887746afc0ef351b8c511a8c3086ac763e2c",
          "sha256": "d2bed3a54e8f0cf344354252ac9dca076a0d609106cf9a6c437bb524f8eb7755",
          "sha1": "0628265d689f0d9005676014d49ce1c953d84986",
          "md5": "8b46fdf506660f88133166585dbe5d83"
        }
      ]
    }
  ]
}
