{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "roscpp_tutorials",
    "version": "0.10.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2.jar",
          "url": "roscpp_tutorials-0.10.2.jar",
          "size": 1555,
          "sha512": "23bfff865c3752c4ee45eada137188f5c7aa3919539fdc41002a3713a99cd337a98204ce6730e52d518a622f1be7e0abfc9c8ac37b8fc8e4e128b2c2697c9bc8",
          "sha256": "c6e17b99d03fe707dcc0c6899b69dfd02d9f4c0b5c0b0cb0b4cfb1680561e75a",
          "sha1": "23dea4e29dd648135cd4c58772e6e2192ff09064",
          "md5": "79e9872fe73349385bb06cc6c611706a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "std_msgs",
          "version": {
            "requires": "0.5.13"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        }
      ],
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2.jar",
          "url": "roscpp_tutorials-0.10.2.jar",
          "size": 1555,
          "sha512": "23bfff865c3752c4ee45eada137188f5c7aa3919539fdc41002a3713a99cd337a98204ce6730e52d518a622f1be7e0abfc9c8ac37b8fc8e4e128b2c2697c9bc8",
          "sha256": "c6e17b99d03fe707dcc0c6899b69dfd02d9f4c0b5c0b0cb0b4cfb1680561e75a",
          "sha1": "23dea4e29dd648135cd4c58772e6e2192ff09064",
          "md5": "79e9872fe73349385bb06cc6c611706a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2-sources.jar",
          "url": "roscpp_tutorials-0.10.2-sources.jar",
          "size": 1357,
          "sha512": "ee31c8c67d1328a2c888819a687a88a918a6e6ac92b297b3cf2bb9888269c4d7c8f4034fd452cd5095a3504cde39ed4d4309c5c570b13f52163f6f54d45d0abc",
          "sha256": "dc08f6185b07a4bbfebdbe8768815c5f2d1fadb69ebcb37592ac6a61640b338e",
          "sha1": "861115e52df9b83fd4783f9bc0407912a15f111e",
          "md5": "dcdd920d03e12d69701710a89304de6c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "roscpp_tutorials-0.10.2-javadoc.jar",
          "url": "roscpp_tutorials-0.10.2-javadoc.jar",
          "size": 112259,
          "sha512": "71584113bbb6942137b84a97339b46c9f6e699cf873894f374c68230a1acc17c4dff019aec888ad6e04d0b836fe7c39609a0271dcb276fccf5d969fe08ad4cc2",
          "sha256": "13f14d62d9dcad206ccd7f4f004d7773dd773f4718103a41fe9bc801b22ec644",
          "sha1": "dbbd0b8069e42e5813188e5e3187a649e822dcc5",
          "md5": "fbafa498d46506587a07093e0bee2b40"
        }
      ]
    }
  ]
}
