{
  "formatVersion": "1.1",
  "component": {
    "group": "org.ros.rosjava_messages",
    "module": "navfn",
    "version": "1.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "navfn-1.17.1.jar",
          "url": "navfn-1.17.1.jar",
          "size": 3043,
          "sha512": "e7dba82a7a6883b825c7e413e8f27862aa6f66938457483598d1de2f3b0b4f5966a46eb82197c22fd4615c408c5b641f66e5e6aeb04c9a7826baf759f4a71791",
          "sha256": "ddbece87a200aead12701c7c3745daf26132eaed437e3ae87e36fd004e45aa49",
          "sha1": "ff654d7cf1ea813b60c6f9f9bdfd77c6b2aabe5b",
          "md5": "1d8df94cd63275e3503060ed8f609f75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ros.rosjava_messages",
          "module": "geometry_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "nav_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "sensor_msgs",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "roscpp",
          "version": {
            "requires": "1.15.9"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "costmap_2d",
          "version": {
            "requires": "1.17.1"
          }
        },
        {
          "group": "org.ros.rosjava_messages",
          "module": "visualization_msgs",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "navfn-1.17.1.jar",
          "url": "navfn-1.17.1.jar",
          "size": 3043,
          "sha512": "e7dba82a7a6883b825c7e413e8f27862aa6f66938457483598d1de2f3b0b4f5966a46eb82197c22fd4615c408c5b641f66e5e6aeb04c9a7826baf759f4a71791",
          "sha256": "ddbece87a200aead12701c7c3745daf26132eaed437e3ae87e36fd004e45aa49",
          "sha1": "ff654d7cf1ea813b60c6f9f9bdfd77c6b2aabe5b",
          "md5": "1d8df94cd63275e3503060ed8f609f75"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navfn-1.17.1-sources.jar",
          "url": "navfn-1.17.1-sources.jar",
          "size": 2534,
          "sha512": "bb048c9f08759a1ddb96dfd8d0ea2fd237a2d10b3cb9b575970f926e82fcfa7fbccc87514ab7b1150b1d6a984d37d8b81c5962384bfd2c19f545ca42d7796b01",
          "sha256": "dc537268708d4565fe7c8caef3ca7ac3f1dc24a6b3de8e690366b406324134c3",
          "sha1": "de50454f4dc0c533ee196967214624ca58154aa1",
          "md5": "d050301e31ca9d0930088960708997e5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "navfn-1.17.1-javadoc.jar",
          "url": "navfn-1.17.1-javadoc.jar",
          "size": 119536,
          "sha512": "ea819e5309947e012e82bd426b523c1211b93517d839a2cadb3e27dd8693e61c6f51e12768f19d6d1c2ab6f3ff5b9a25d0f5ed6a407559ee54a3d3fda0a1a0c2",
          "sha256": "14d6e271f938ac2c0118daa69024286765241305d09219400054e2399aa21371",
          "sha1": "98756e592eeb29762bdb8c9d1686637b875a9d61",
          "md5": "300df3fed69189cad9a141a5a8f694aa"
        }
      ]
    }
  ]
}
